=== CSCfi/metadata-submitter/metadata_backend/helpers/schemas/bpannotation.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Bigpicture Annotation",
    "$defs": {
        "attributes": {
            "title": "Attributes",
            "description": "Collection of attributes.",
            "oneOf": [
                {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "anyOf": [
                            {
                                "properties": {
                                    "tag": {
                                        "type": "string",
                                        "title": "Attribute tag"
                                    },
                                    "value": {
                                        "type": [
                                            "string",
                                            "number",
                                            "null"
                                        ],
                                        "title": "Attribute value"
                                    }
                                },
                                "required": [
                                    "tag",
                                    "value"
                                ]
                            },
                            {
                                "properties": {
                                    "tag": {
                                        "type": "string",
                                        "title": "Attribute tag"
                                    },
                                    "value": {
                                        "type": "number",
                                        "title": "Attribute value"
                                    },
                                    "units": {
                                        "type": "string",
                                        "description": "Scientific units of the value."
                                    }
                                },
                                "required": [
                                    "tag",
                                    "value",
                                    "units"
                                ]
                            },
                            {
                                "properties": {
                                    "tag": {
                                        "type": "string",
                                        "title": "Attribute tag"
                                    },
                                    "value": {
                                        "type": "object",
                                        "title": "Attribute value",
                                        "properties": {
                                            "code": {
                                                "type": "string",
                                                "title": "The code value."
                                            },
                                            "scheme": {
                                                "type": "string",
                                                "title": "The scheme designator of the code."
                                            },
                                            "meaning": {
                                                "type": "string",
                                                "title": "Cleartext meaning of the code."
                                            },
                                            "schemeVersion": {
                                                "type": [
                                                    "string",
                                                    "null"
                                                ],
                                                "title": "Optional scheme version of the scheme designator."
                                            }
                                        },
                                        "required": [
                                            "code",
                                            "scheme",
                                            "meaning",
                                            "schemeVersion"
                                        ]
                                    }
                                },
                                "required": [
                                    "tag",
                                    "value"
                                ]
                            },
                            {
                                "properties": {
                                    "tag": {
                                        "type": "string",
                                        "title": "Attribute tag"
                                    },
                                    "value": {
                                        "type": "object",
                                        "title": "Attribute value",
                                        "description": "These will only occur when parsing a setAttribute.",
                                        "properties": {
                                            "stringAttribute": {
                                                "anyOf": [
                                                    {
                                                        "refs": "#/$defs/attributes"
                                                    },
                                                    {
                                                        "type": "object",
                                                        "properties": {
                                                            "tag": {
                                                                "type": "string"
                                                            },
                                                            "value": {
                                                                "type": "string"
                                                            }
                                                        },
                                                        "required": [
                                                            "tag",
                                                            "value"
                                                        ]
                                                    }
                                                ]
                                            },
                                            "numericAttribute": {
                                                "anyOf": [
                                                    {
                                                        "refs": "#/$defs/attributes"
                                                    },
                                                    {
                                                        "type": "object",
                                                        "properties": {
                                                            "tag": {
                                                                "type": "string"
                                                            },
                                                            "value": {
                                                                "type": "number"
                                                            }
                                                        },
                                                        "required": [
                                                            "tag",
                                                            "value"
                                                        ]
                                                    }
                                                ]
                                            },
                                            "measurementAttribute": {
                                                "anyOf": [
                                                    {
                                                        "refs": "#/$defs/attributes"
                                                    },
                                                    {
                                                        "type": "object",
                                                        "properties": {
                                                            "tag": {
                                                                "type": "string"
                                                            },
                                                            "value": {
                                                                "type": "string"
                                                            },
                                                            "units": {
                                                                "type": "string"
                                                            }
                                                        },
                                                        "required": [
                                                            "tag",
                                                            "value",
                                                            "units"
                                                        ]
                                                    }
                                                ]
                                            },
                                            "codeAttribute": {
                                                "anyOf": [
                                                    {
                                                        "refs": "#/$defs/attributes"
                                                    },
                                                    {
                                                        "type": "object",
                                                        "properties": {
                                                            "tag": {
                                                                "type": "string",
                                                                "title": "Attribute tag"
                                                            },
                                                            "value": {
                                                                "type": "object",
                                                                "title": "Attribute value",
                                                                "properties": {
                                                                    "code": {
                                                                        "type": "string",
                                                                        "title": "The code value."
                                                                    },
                                                                    "scheme": {
                                                                        "type": "string",
                                                                        "title": "The scheme designator of the code."
                                                                    },
                                                                    "meaning": {
                                                                        "type": "string",
                                                                        "title": "Cleartext meaning of the code."
                                                                    },
                                                                    "schemeVersion": {
                                                                        "type": [
                                                                            "string",
                                                                            "null"
                                                                        ],
                                                                        "title": "Optional scheme version of the scheme designator."
                                                                    }
                                                                },
                                                                "required": [
                                                                    "code",
                                                                    "scheme",
                                                                    "meaning",
                                                                    "schemeVersion"
                                                                ]
                                                            }
                                                        },
                                                        "required": [
                                                            "tag",
                                                            "value"
                                                        ]
                                                    }
                                                ]
                                            },
                                            "setAttribute": {
                                                "type": [
                                                    "array",
                                                    "object"
                                                ],
                                                "description": "Contents of setAttribute are difficult to specify more specifically than this."
                                            }
                                        },
                                        "anyOf": [
                                            {
                                                "required": [
                                                    "stringAttribute"
                                                ]
                                            },
                                            {
                                                "required": [
                                                    "numericAttribute"
                                                ]
                                            },
                                            {
                                                "required": [
                                                    "measurementAttribute"
                                                ]
                                            },
                                            {
                                                "required": [
                                                    "codeAttribute"
                                                ]
                                            },
                                            {
                                                "required": [
                                                    "setAttribute"
                                                ]
                                            }
                                        ]
                                    }
                                },
                                "required": [
                                    "tag",
                                    "value"
                                ]
                            }
                        ]
                    }
                },
                {
                    "type": "null",
                    "description": "If attributes element was allowed to be nillable and thus left empty."
                }
            ]
        },
        "reference": {
            "additionalProperties": true,
            "type": "object",
            "required": [
                "alias"
            ],
            "properties": {
                "alias": {
                    "type": "string",
                    "description": "Identifies an object by alias designated by the submitter.",
                    "title": "Alias"
                },
                "accession": {
                    "type": "string",
                    "description": "Identifies a record by its accession. The scope of resolution is the entire Archive. Should not be present when submitting.",
                    "title": "Accession"
                }
            }
        },
        "annotationFile": {
            "title": "Annotation File Type",
            "type": "object",
            "required": [
                "filetype",
                "filename",
                "checksumMethod",
                "checksum"
            ],
            "properties": {
                "filetype": {
                    "title": "File Type",
                    "description": "The type of the file.",
                    "type": "string",
                    "enum": [
                        "dcm",
                        "json"
                    ]
                },
                "filename": {
                    "title": "File Name",
                    "description": "The file name.",
                    "type": "string"
                },
                "checksumMethod": {
                    "title": "Checksum Method",
                    "description": "Checksum generated by the SHA256 method.",
                    "type": "string",
                    "enum": [
                        "SHA256"
                    ]
                },
                "checksum": {
                    "title": "Checksum",
                    "description": "The file checksum. (string consisting of exactly 64 characters)",
                    "type": "string"
                }
            }
        }
    },
    "type": "object",
    "description": "An annotation object captures annotation objects.",
    "additionalProperties": true,
    "required": [
        "alias",
        "imageRef",
        "files",
        "attributes"
    ],
    "properties": {
        "alias": {
            "title": "Object alias",
            "description": "Submitter designated name for the object. The name must be unique within the Study and Dataset the entity belongs to.",
            "type": "string"
        },
        "accession": {
            "title": "Object accession ID",
            "description": "The object accession assigned by the archive. Should not be present when submitting.",
            "type": "string"
        },
        "imageRef": {
            "title": "Image Reference",
            "description": "Image associated with the annotation.",
            "$ref": "#/$defs/reference"
        },
        "files": {
            "title": "Files",
            "description": "Data files associated with the annotation.",
            "type": "array",
            "items": {
                "$ref": "#/$defs/annotationFile"
            }
        },
        "attributes": {
            "$ref": "#/$defs/attributes"
        }
    }
}

=== CSCfi/metadata-submitter/tests/test_files/bpannotation/annotation.json
{
    "alias": "Annotation_12345",
    "imageRef": {
        "alias": "Image_12345"
    },
    "files": [
        {
            "filename": "project/folder/file.dcm",
            "checksumMethod": "SHA256",
            "checksum": "123456789012345678901234567890123456789012345678901234567890abcd",
            "filetype": "dcm"
        },
        {
            "filename": "project/folder/file.json",
            "checksumMethod": "SHA256",
            "checksum": "abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcd",
            "filetype": "json"
        }
    ],
    "attributes": null
}
